# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Python - Inside Out
tagline:          'We put the "crash" in crash course'
description:      'Explore Python with me! OOP, data structures, algorithms, and data science methods'
url:              https://bradleyjay.github.io
baseurl:          /

author:
  name:           'Bradley Jay'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bradleyjay/bradleyjay.github.io
