# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Python Strugglebus
tagline:          'Where learning and doing never happen'
description:      'Come learn Python with me! Struggles and solutions. The struggle is real.'
url:              https://bradleyjay.github.io
baseurl:          /

author:
  name:           'Bradley Jay'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bradleyjay/bradleyjay.github.io
